# Generated by Django 4.0.4 on 2022-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
